# Sprint 19 calibration configuration example
symbols: ["BTCUSDT"]
timeframes: ["5m"]
walk_forward:
  analysis_start_date: "2023-01-01"
  analysis_end_date:   "2023-06-01"
  window:
    train_period:  "4w"
    test_period:   "1w"
    advance_by:    "1w"
  data_rules:
    purge_period:  "2d"
    embargo_period: "1d"

objective:
  weights:
    profit_factor:  0.35
    winrate:        0.25
    sharpe:         0.15
    max_drawdown:  -0.15
    oos_stability:  0.10
  penalties:
    min_trades: 60
    overfit_gap: 0.15

search_space:
  ensemble:
    vote_threshold_trend:   {low: 0.40, high: 0.75}
    vote_threshold_mr:      {low: 0.35, high: 0.65}
    confidence_floor:       {low: 0.50, high: 0.80}
    margin_of_victory:      {low: 0.05, high: 0.30}
    min_agree_trend:        {low: 1, high: 3, step: 1}
    min_agree_mr:           {low: 1, high: 3, step: 1}
  playbooks_trend_breakout:
    min_adx:                {low: 18, high: 30}
    ema_sep_atr_min:        {low: 0.15, high: 0.45}
    stop_atr_mult:          {low: 1.1, high: 1.7}
    tp1_atr_mult:           {low: 1.4, high: 2.2}
    rr_min:                 {low: 1.2, high: 1.8}
  playbooks_mr_fade:
    rsi_low:                {low: 20, high: 35}
    rsi_high:               {low: 65, high: 80}
    stop_atr_mult:          {low: 0.8, high: 1.3}
    tp1_atr_mult:           {low: 1.1, high: 1.8}
    rr_min:                 {low: 1.1, high: 1.6}
  quality_gates:
    q_Aplus:                {low: 0.80, high: 0.90}
    q_A:                    {low: 0.70, high: 0.85}
    q_C:                    {low: 0.50, high: 0.65}
    max_spread_pct:         {low: 0.03, high: 0.08}
    atr_pct_limit:          {low: 0.92, high: 0.98}
  sizing:
    base_risk_pct:          {low: 0.005, high: 0.025}
    trend_size_scale:       {low: 0.9, high: 1.3}
    mr_size_scale:          {low: 0.7, high: 1.1}
    liq_risk_weight:        {low: 0.3, high: 1.0}
  orderflow:
    cvd_weight:             {low: 0.2, high: 0.6}
    liquidation_weight:     {low: 0.1, high: 0.5}
    sweep_weight:           {low: 0.1, high: 0.5}
  slippage:
    atr_multiplier:         {low: 0.05, high: 0.30}

runtime:
  trials: 30   # reduced for smoke testing; increase later
  seed: 42
  cache_data: true
  save_study_db: true
  save_topk: 10

# Default pattern detection configuration (Sprint 66)
patterns:
  enabled: true
  pivots:
    fractal_k: 2
  geom:
    # min R^2 for regression fits (0 disables R^2 gating)
    min_r2: 0.0
  triangle:
    min_pivots: 3
  wedge:
    min_pivots: 3
  flag:
    run_pct_min: 0.03
    band_max: 0.02
  cup:
    min_length: 9
    handle_proximity: 0.9
