runtime:
  symbols: ["BTCUSDT"]
  timeframes: ["5m"]
  primary_timeframe: "5m"
  reconnect_backoff_ms: 2000

data_sources:
  binance_usdm: { api_key: null, api_secret: null }

features:
  warmup_periods: 120
  trend: { ema_short: 8, ema_medium: 21, ema_long: 55, adx_period: 14 }
  momentum: { rsi_period: 14, macd_fast: 12, macd_slow: 26, macd_signal: 9 }
  volatility: { atr_period: 14, bbands_period: 20, bbands_stddev: 2 }
  volume_flow: { vwap_window: 20, vwap_std_devs: [1.0,2.0], volume_z_window: 50 }

derivatives: { funding_trail_len: 4, funding_refresh_sec: 900, oi: { enabled: false, provider: mock, refresh_sec: 60 }, liq_pulse: { window_sec: 300, notional_weight: 1.0 } }
regime: { hysteresis_bars: 3, adx_min_trend: 15, atr_percentile_windows: 200, variance_ratio_window: 20 }
weights_profiles:
  trend: { trend: 0.3, momentum: 0.2, volatility: 0.2, flow: 0.2, orderbook: 0.05, derivatives: 0.05 }
  mean_revert: { trend: 0.2, momentum: 0.3, volatility: 0.2, flow: 0.2, orderbook: 0.05, derivatives: 0.05 }
  chop: { trend: 0.2, momentum: 0.25, volatility: 0.25, flow: 0.2, orderbook: 0.05, derivatives: 0.05 }
filters: { avoid_funding_minutes: 5 }
engine:
  scoring_weights: { trend: 1, momentum: 1, volatility: 1 }
  thresholds: { enter: 0.5, exit: 0.4 }
  risk: { max_spread_pct: { default: 0.05 } }
ensemble: { min_score: 0.05, majority_threshold: 0.55, veto_trend_flip: true, veto_band_pierce: true }
correlation: { enabled: false, lookback_periods: 100, cluster_threshold: 0.7, hysteresis: 0.1, refresh_interval_bars: 50 }
portfolio: { max_exposure_per_symbol: 1000, max_exposure_per_cluster: 3000, max_net_exposure: 5000, max_margin_pct: 50, max_total_positions: 10, max_positions_total: 10, max_positions_per_symbol: 1, allow_scale_in: false, scale_in_cooldown_bars: 0, scale_in_min_distance_pct: 0.0 }
brakes: { min_spacing_sec_cluster: 300, daily_loss_soft_limit_pct: 2.0, daily_loss_hard_limit_pct: 4.0, streak_cooldown_trades: 3, streak_cooldown_hours: 12 }
sizing: { vol_risk_scale_pct: 0.5 }
funding_rate_provider: { refresh_interval_minutes: 15 }
transport: { telegram: { enabled: false, bot_token: null, chat_id: null }, dry_run: true }
reports: { output_dir: reports }
logging: { level: INFO }

# Meta scorer label config placeholder
meta_scorer:
  label:
    type: tp_before_sl
  synthetic_min_pos: 6
  negative_sampling:
    ratio: 1.0  # 1 negative per positive
    max: 100

# Sentiment default config (topic-aware)
sentiment:
  enabled: true
  cache_dir: ".cache/sentiment"
  symbols: ["BTCUSDT","ETHUSDT"]
  sources:
    twitter: { enabled: true, refresh_sec: 900 }
    reddit: { enabled: true, refresh_sec: 900 }
    telegram: { enabled: false }
    funding: { enabled: true, refresh_sec: 900 }
  source_weights:
    influencer: 3.0
    twitter: 1.5
    reddit: 1.0
    telegram: 0.8
    news: 0.7
  influencers: {}
  topic_taxonomy_path: null
  funding_threshold: 0.0003
  oi_threshold_pct: 0.02
  extremes: { z_threshold: 2.0 }
  telemetry: { emit_metrics: true, interval_sec: 300 }

# Example: register emitted topic features with Meta-Scorer stacker mapping (S31)
meta_scorer:
  enabled: true
  input_features:
    - sent_topic_etf_regulation_score_s
    - sent_topic_etf_regulation_z
    - sent_topic_etf_regulation_pctl
    - sent_topic_hack_exploit_score_s
    - sent_topic_meme_retail_score_s
    - sent_vs_funding_div_long
    - sent_vs_funding_div_short
    - contrarian_flag_long
    - contrarian_flag_short
  missing_policy: SAFE