# Ultra-Signals Settings - v0.1

data_sources:
  binance_usdm:
    api_key: "qWV8egLZudf3GNzt2LygfMfgqr6Hw2gWbXE9RjwP6VVhF9Sif9qVY1vot9cr1RsV"
    api_secret: "2LjccLY6enls0g5hE1MqeC9jMmrSArhezIfm6X4ZcyUhS2xUSisxELZreSwebPjm"

runtime:
  symbols: ["BTCUSDT", "ETHUSDT", "BNBUSDT"]
  timeframes: ["1m", "5m"]
  primary_timeframe: "5m"
  reconnect_backoff_ms: 2000

features:
  warmup_periods: 200
  trend:
    ema_short: 20
    ema_medium: 50
    ema_long: 200
  momentum:
    rsi_period: 14
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
  volatility:
    atr_period: 14
    bbands_period: 20
    bbands_stddev: 2.0
  volume_flow:
    vwap_window: 20
    vwap_std_devs: [1.0, 2.0]
    volume_z_window: 50
  flow_metrics:  # Sprint 11 advanced flow pack
    enabled: true
    cvd:
      min_strength: 0.15
    oi:
      spike_threshold: 0.12
    liquidations:
      min_cluster_size: 3
      atr_normed: true
    depth_imbalance:
      min_strength: 0.1
    spread:
      max_bp: 5
    volume:
      z_threshold: 2.5

derivatives:
  funding_trail_len: 8
  funding_refresh_sec: 900
  oi:
    enabled: true
    provider: "mock"
    refresh_sec: 60
  liq_pulse:
    window_sec: 300
    notional_weight: 1.0

# --- NEW / UPDATED REGIME CONFIG (Sprint 10) ---
regime:
  enabled: true
  cooldown_bars: 8
  strong_override: true
  hysteresis_hits: 2
  primary:
    trend:
      enter:
        adx_min: 24
        ema_sep_atr_min: 0.35
      exit:
        adx_min: 18
        ema_sep_atr_min: 0.20
    mean_revert:
      enter:
        adx_max: 16
        bb_width_pct_atr_max: 0.70
      exit:
        adx_max: 20
    chop:
      enter:
        adx_max: 20
      exit:
        adx_max: 24
  vol:
    expansion_atr_pct: 0.70
    crush_atr_pct: 0.20
  liquidity:
    max_spread_bp: 3.0
    min_volume_z: -1.0

# Sprint 13 Regime Detection (router heuristics)
regime_detection:
  adx_threshold: 22
  chop_volatility: 15          # ATR percentile or bb width pct threshold
  mean_revert_rsi: 70          # RSI extreme to bias mean reversion
  lookback_bars: 50

# Sprint 13 Alpha Profiles (regime-aware alpha fusion)
alpha_profiles:
  trend:
    alphas: ["breakout_v2", "volume_surge", "oi_pump"]
    weight_scale: 1.2
    min_confidence: 0.60
  mean_revert:
    alphas: ["bollinger_fade", "rsi_extreme", "cvd_reversal"]
    weight_scale: 1.1
    min_confidence: 0.55
  chop:
    alphas: ["none"]
    weight_scale: 0.2
    min_confidence: 0.70

# Sprint 14 Order Flow confirmation
orderflow:
  enable: true
  cvd_weight: 0.4
  liquidation_weight: 0.3
  liquidity_sweep_weight: 0.3
  liquidation_threshold: 1000000    # USD threshold for major liquidation side dominance
  cvd_window: 20                    # (future) smoothing window
  sweep_imbalance_threshold: 2.5    # bid/ask aggregate imbalance to flag sweep

# Sprint 15 Dynamic Position Sizing + Liquidation Heatmap
position_sizing:
  enabled: true
  max_risk_pct: 0.02         # Risk 2% of balance per trade
  min_confidence: 0.55       # Skip signals below this ensemble+orderflow confidence
  atr_window: 14
  liq_risk_weight: 0.6       # Scales down size when near liquidation clusters
  skip_high_liq_risk: true   # If liq risk > threshold, drop trade
  liq_risk_skip_threshold: 1.5

liquidation_heatmap:
  enabled: true
  api_source: "mock"          # placeholder (tensorcharts, coinalyze, etc.)
  min_cluster_usd: 1000000   # Only consider large clusters
  proximity_lookback: 50     # bars to consider for recent cluster relevance (placeholder)

# Sprint 16 News & Volatility Veto System
news_veto:
  enabled: true
  sources:
    - local_file: "news_events.yaml"
  embargo_minutes: 15
  high_impact_only: true

volatility_veto:
  enabled: true
  atr_percentile_limit: 0.95
  liq_cluster_sensitivity: high   # high|medium|low
  funding_rate_limit: 0.0005      # 0.05% expressed as decimal

# Sprint 18 Quality Gates (confidence binning + targeted vetoes)
quality_gates:
  enabled: true
  # qscore bin thresholds (D below C)
  qscore_bins: { Aplus: 0.85, A: 0.75, B: 0.65, C: 0.55 }
  # bin action policy
  bin_actions:
    Aplus: { size_mult: 1.30, require_extra_confirm: false }
    A:     { size_mult: 1.15, require_extra_confirm: false }
    B:     { size_mult: 1.00, require_extra_confirm: false }
    C:     { size_mult: 0.75, require_extra_confirm: true }
    D:     { size_mult: 0.00, require_extra_confirm: true }
  weights:
    ensemble_conf: 0.40
    orderflow: 0.20
    regime_fit: 0.20
    expected_rr: 0.20
  veto:
    max_spread_pct: 0.06
    max_book_staleness_ms: 2500
    max_missing_bars: 2
    atr_pct_limit: 0.97
    near_heatmap_bp: 8
    max_slippage_rr_drop: 0.2
    corr_leader: "BTCUSDT"
    corr_lookback: 96
    corr_threshold: 0.75
    daily_loss_limit_pct: 0.06
    max_consecutive_losses: 4
  soft:
    ofi_conflict_limit: -0.15
    late_move_atr: 0.8
    min_volume_z: -0.8
    restricted_hours_utc:
      - { start: "00:00", end: "00:30" }

# Sprint 17 Regime-Adaptive Playbooks
playbooks:
  trend:
    breakout:
      enabled: true
      entry:
        min_conf: 0.62
        min_adx: 22
        ema_sep_atr_min: 0.30
        of_confirm: { cvd: 0.05 }
      exit:
        stop_atr_mult: 1.4
        tp_atr_mults: [1.8, 2.6, 3.4]
        trail_after_rr: 1.5
        timeout_bars: 6
      risk:
        size_scale: 1.15
        cooldown_bars: 6
        rr_min: 1.4

    pullback:
      enabled: true
      entry:
        min_conf: 0.60
        min_adx: 20
        ema_sep_atr_min: 0.20
        of_confirm: { cvd: 0.00 }
      exit:
        stop_atr_mult: 1.2
        tp_atr_mults: [1.6, 2.2, 3.0]
        trail_after_rr: 1.3
        timeout_bars: 8
      risk:
        size_scale: 1.05
        cooldown_bars: 6
        rr_min: 1.3

  mean_revert:
    bb_fade:
      enabled: true
      entry:
        min_conf: 0.58
        rsi_extreme: [28, 72]
        of_confirm: { liq_cluster_side: "long_liq|short_liq" }
      exit:
        stop_atr_mult: 1.0
        tp_atr_mults: [1.2, 1.8, 2.4]
        trail_after_rr: 1.2
        timeout_bars: 6
      risk:
        size_scale: 0.9
        cooldown_bars: 5
        rr_min: 1.2

    vwap_revert:
      enabled: true
      entry:
        min_conf: 0.60
        of_confirm: { sweep: true }
      exit:
        stop_atr_mult: 1.1
        tp_atr_mults: [1.4, 2.0]
        timeout_bars: 5
      risk:
        size_scale: 0.95
        cooldown_bars: 5
        rr_min: 1.25

  chop:
    flat:
      enabled: true

weights_profiles:
  trend:       {trend: 0.30, momentum: 0.22, volatility: 0.08, flow: 0.18, orderbook: 0.08, derivatives: 0.14}
  mean_revert: {trend: 0.15, momentum: 0.22, volatility: 0.13, flow: 0.22, orderbook: 0.13, derivatives: 0.15}
  chop:        {trend: 0.10, momentum: 0.20, volatility: 0.20, flow: 0.25, orderbook: 0.15, derivatives: 0.10}
  # Optional Sprint 11 per-profile weights for new flow metrics (cvd, oi_rate, liquidation_pulse, depth_imbalance)
  # Provide only if you want to overweight them; else ensemble defaults to 1.0 when reading.
  #trend:
  #  cvd: 1.2
  #  oi_rate: 1.0
  #  liquidation_pulse: 1.5
  #  depth_imbalance: 0.8

filters:
  avoid_funding_minutes: 5
  atr_gate_pct: 60
  adx_min: 20
  tr_compression_max: 0.25

engine:
  scoring_weights:
    trend: 0.5
    momentum: 0.5
    volatility: 0.0
  thresholds:
    enter: 0.1
    exit: 0.4
  risk:
    max_spread_pct:
      default: 0.06
      "1000SHIBUSDT": 0.1

ensemble:
  min_score: 0.05
  majority_threshold: 0.50
  veto_trend_flip: true
  veto_band_pierce: true
  vote_threshold:
    trend: 0.60
    mean_revert: 0.58
    chop: 0.60
    mixed: 0.60
  min_agree:
    trend: 2
    mean_revert: 2
    chop: 2
    mixed: 2
  margin_of_victory: 0.08
  confidence_floor: 0.60
  use_prob_mass: true

correlation:
  enabled: true
  lookback_periods: 200
  cluster_threshold: 0.7
  hysteresis: 0.1
  refresh_interval_bars: 50

veto:
  near_funding_window_min: 20
  wide_spread_bps: 6
  enable_liq_spike_contra: true
  enable_cvd_alignment: false
  enable_depth_thin_check: true

confluence:
  map: { "5m": "15m", "15m": "1h", "1h": "4h" }
  require_regime_align: true

alpha:
  funding:
    enabled: true
    source: "csv"
    dir: "data/funding"
    fallback_rate: 0.0001
  cvd:
    enabled: true
    method: "ohlcv_proxy"
    lookback: 200
    slope_window: 20
    slope_threshold: 0.1
  liquidations:
    enabled: true
    source: "csv"
    dir: "data/liquidations"
    spike_window: 50
    spike_zscore: 3.0
  depth:
    enabled: true
    exchanges: ["binance", "bybit"]
    thin_spread_bps: 12
    min_top_qty: 0.0

news_filter:
  enabled: true
  file: "data/calendar/events.json"
  window_minutes: 30
  min_severity: 2

portfolio:
  max_exposure_per_symbol: 1000.0
  max_exposure_per_cluster: 3000.0
  max_net_exposure: 5000.0
  max_margin_pct: 50.0
  global_entry_budget: 0
  max_total_positions: 10
  max_positions_per_symbol: 3

brakes:
  min_spacing_sec_cluster: 300
  daily_loss_soft_limit_pct: 2.0
  daily_loss_hard_limit_pct: 4.0
  streak_cooldown_trades: 3
  streak_cooldown_hours: 12

sizing:
  vol_risk_scale_pct: 0.5
  base_risk_pct: 0.010
  kelly_cap: 0.75
  rr_fallback: 1.2

# Sprint 12 Adaptive Risk Model
risk_model:
  enabled: true
  base_risk_pct: 0.02
  max_leverage: 10
  min_confidence: 0.55
  regime_risk:
    trend: 1.2
    mean_revert: 1.0
    chop: 0.5
  atr_multiplier_stop: 2.5
  atr_multiplier_tp: 3.0
  tighten_tp_on_liq_cluster: true
  liq_tp_tighten_factor: 0.7  # multiply TP distance when recent liquidation cluster

funding_rate_provider:
  refresh_interval_minutes: 15

transport:
  telegram:
    enabled: true
    bot_token: null
    chat_id: null
  dry_run: true

backtest:
  start_date: "2023-01-01"
  end_date: "2023-01-31"
  data:
    provider: "csv"
    base_path: "data"
    cache_path: ".cache/data"
  execution:
    initial_capital: 10000.0
    default_size_pct: 1.0
    fee_bps: 4.0
    slippage_model: "atr"
    tp_pct: 0.05
    sl_pct: 0.05
    max_bars_in_trade: 36

reports:
  output_dir: "reports"

logging:
  level: "DEBUG"
