redis:
  enabled: true
  host: localhost
  port: 6379
  db: 0
  password: null
  timeout: 5.0
prometheus:
  enabled: true
  port: 8000
  path: /metrics
data_sources:
  binance_usdm:
    api_key: null
    api_secret: null
data_quality:
  enabled: true
  max_clock_skew_ms: 250
  max_bar_start_skew_ms: 120
  server_time_check_secs: 30
  ntp_fallback_enabled: true
  ntp_servers:
  - pool.ntp.org
  - time.google.com
  allow_equal_timestamps: false
  drop_duplicates: true
  max_out_of_order_ms: 2000
  gap_policy:
    min_bar_coverage_pct: 95
    heal_backfill_bars: 50
    fail_on_large_gap_bars: 6
    impute_method: prev_close
  tz: UTC
  ohlcv_schema:
  - ts
  - open
  - high
  - low
  - close
  - volume
  strict_numeric: true
  price_decimals_max: 8
  volume_decimals_max: 8
  multi_venue:
    primary:
    - BINANCE
    - BYBIT
    - OKX
    max_spread_bps: 12
    merge_mode: best_bid_ask
  aligners:
    funding_window_sec: 60
    require_within_sec: 90
    basis_calc_enabled: true
  venue_status:
    check_interval_sec: 60
    require_operational: true
    grace_period_sec: 180
  heartbeats:
    market_data_max_silence_sec: 20
    order_events_max_silence_sec: 30
    action_on_silence: circuit_break
  report_dir: reports/data_quality
  write_parquet_snaps: true
  symbols:
    map_path: config/symbol_map.yaml
runtime:
  symbols:
  - BTCUSDT
  - ETHUSDT
  - SOLUSDT
  - BNBUSDT
  - XRPUSDT
  - DOGEUSDT
  - ADAUSDT
  - AVAXUSDT
  - LINKUSDT
  - TONUSDT
  - TRXUSDT
  - DOTUSDT
  - NEARUSDT
  - ATOMUSDT
  - LTCUSDT
  - BCHUSDT
  - ARBUSDT
  - APTUSDT
  - MATICUSDT
  - SUIUSDT
  timeframes:
  - 1m
  - 3m
  - 5m
  - 15m
  primary_timeframe: 1m   # canary override (was 5m) to force per-minute evaluation
  reconnect_backoff_ms: 2000
  sniper_mode:
    enabled: true
    mtf_confirm: true
  min_confidence: 0.65        # raised from 0.60 for higher signal selectivity
  max_signals_per_hour: 30    # raised from 2 to surface candidates during tuning
  daily_signal_cap: 200       # raised from 6 to avoid artificial scarcity in canary
  cooldown_bars: 10
features:
  warmup_periods: 20    # reduced from 200 for faster canary; note with 5m primary this is ~100 mins
  trend:
    ema_short: 20
    ema_medium: 50
    ema_long: 200
  momentum:
    rsi_period: 14
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
  volatility:
    atr_period: 14
    bbands_period: 20
    bbands_stddev: 2.0
  volume_flow:
    vwap_window: 20
    vwap_std_devs:
    - 1.0
    - 2.0
    volume_z_window: 50
  flow_metrics:
    enabled: true
    cvd:
      min_strength: 0.15
    oi:
      spike_threshold: 0.12
    liquidations:
      min_cluster_size: 3
      atr_normed: true
    depth_imbalance:
      min_strength: 0.1
    spread:
      max_bp: 5
    volume:
      z_threshold: 2.5
derivatives:
  funding_trail_len: 8
  funding_refresh_sec: 900
  oi:
    enabled: true
    provider: mock
    refresh_sec: 60
  liq_pulse:
    window_sec: 300
    notional_weight: 1.0
regime:
  enabled: true
  cooldown_bars: 8
  strong_override: true
  hysteresis_hits: 2
  primary:
    trend:
      enter:
        adx_min: 24
        ema_sep_atr_min: 0.35
      exit:
        adx_min: 18
        ema_sep_atr_min: 0.2
    mean_revert:
      enter:
        adx_max: 16
        bb_width_pct_atr_max: 0.7
      exit:
        adx_max: 20
    chop:
      enter:
        adx_max: 20
      exit:
        adx_max: 24
  vol:
    expansion_atr_pct: 0.7
    crush_atr_pct: 0.2
  liquidity:
    max_spread_bp: 3.0
    min_volume_z: -1.0
regime_detection:
  adx_threshold: 22
  chop_volatility: 15
  mean_revert_rsi: 70
  lookback_bars: 50
alpha_profiles:
  trend:
    alphas:
    - breakout_v2
    - volume_surge
    - oi_pump
    weight_scale: 1.2
  min_confidence: 0.65        # was 0.60
  mean_revert:
    alphas:
    - bollinger_fade
    - rsi_extreme
    - cvd_reversal
    weight_scale: 1.1
  min_confidence: 0.60        # was 0.55
  chop:
    alphas:
    - none
    weight_scale: 0.2
    min_confidence: 0.7
orderflow:
  enable: true
  cvd_weight: 0.4
  liquidation_weight: 0.3
  liquidity_sweep_weight: 0.3
  liquidation_threshold: 1000000
  cvd_window: 20
  sweep_imbalance_threshold: 2.5
position_sizing:
  enabled: true
  max_risk_pct: 0.02
  min_confidence: 0.60          # gate tightened (was 0.55)
  atr_window: 14
  liq_risk_weight: 0.6
  skip_high_liq_risk: true
  liq_risk_skip_threshold: 1.5
liquidation_heatmap:
  enabled: true
  api_source: mock
  min_cluster_usd: 1000000
  proximity_lookback: 50
news_veto:
  enabled: true
  sources:
  - local_file: news_events.yaml
  embargo_minutes: 15
  high_impact_only: true
volatility_veto:
  enabled: true
  atr_percentile_limit: 0.95
  liq_cluster_sensitivity: high
  funding_rate_limit: 0.00035   # tightened from 0.0005 (0.05% -> 0.035-0.04%)
quality_gates:
  enabled: true
  qscore_bins:
  Aplus: 0.85
  A: 0.80        # was 0.75
  B: 0.70        # was 0.65
  C: 0.60        # was 0.55
  bin_actions:
    Aplus:
      size_mult: 1.3
      require_extra_confirm: false
    A:
      size_mult: 1.15
      require_extra_confirm: false
    B:
      size_mult: 1.0
      require_extra_confirm: false
    C:
      size_mult: 0.75
      require_extra_confirm: true
    D:
      size_mult: 0.0
      require_extra_confirm: true
  weights:
    ensemble_conf: 0.4
    orderflow: 0.2
    regime_fit: 0.2
    expected_rr: 0.2
  veto:
    max_spread_pct: 0.02        # tightened from 0.06 for majors
    max_book_staleness_ms: 2000 # tightened from 2500 (data health hard veto)
    max_missing_bars: 2
    atr_pct_limit: 0.95         # align with ~95th percentile cap
    near_heatmap_bp: 8
    max_slippage_rr_drop: 0.2
    corr_leader: BTCUSDT
    corr_lookback: 96
    corr_threshold: 0.75
    daily_loss_limit_pct: 0.04  # align with hard 4% policy
    max_consecutive_losses: 4
    max_last_trade_gap_ms: 3000 # new: hard veto if last trade gap exceeds 3s
  soft:
    ofi_conflict_limit: -0.15
    late_move_atr: 0.8
    min_volume_z: -0.8
    restricted_hours_utc:
    - start: 00:00
      end: 00:30
playbooks:
  trend:
    breakout:
      enabled: true
      entry:
        min_conf: 0.62
        min_adx: 22
        ema_sep_atr_min: 0.3
        of_confirm:
          cvd: 0.05
      exit:
        stop_atr_mult: 1.4
        tp_atr_mults:
        - 1.8
        - 2.6
        - 3.4
        trail_after_rr: 1.5
        timeout_bars: 6
      risk:
        size_scale: 1.15
        cooldown_bars: 6
        rr_min: 1.4
    pullback:
      enabled: true
      entry:
        min_conf: 0.6
        min_adx: 20
        ema_sep_atr_min: 0.2
        of_confirm:
          cvd: 0.0
      exit:
        stop_atr_mult: 1.2
        tp_atr_mults:
        - 1.6
        - 2.2
        - 3.0
        trail_after_rr: 1.3
        timeout_bars: 8
      risk:
        size_scale: 1.05
        cooldown_bars: 6
        rr_min: 1.3
  mean_revert:
    bb_fade:
      enabled: true
      entry:
        min_conf: 0.58
        rsi_extreme:
        - 28
        - 72
        of_confirm:
          liq_cluster_side: long_liq|short_liq
      exit:
        stop_atr_mult: 1.0
        tp_atr_mults:
        - 1.2
        - 1.8
        - 2.4
        trail_after_rr: 1.2
        timeout_bars: 6
      risk:
        size_scale: 0.9
        cooldown_bars: 5
        rr_min: 1.2
    vwap_revert:
      enabled: true
      entry:
        min_conf: 0.6
        of_confirm:
          sweep: true
      exit:
        stop_atr_mult: 1.1
        tp_atr_mults:
        - 1.4
        - 2.0
        timeout_bars: 5
      risk:
        size_scale: 0.95
        cooldown_bars: 5
        rr_min: 1.25
  chop:
    flat:
      enabled: true
weights_profiles:
  trend:
    trend: 0.3
    momentum: 0.22
    volatility: 0.08
    flow: 0.18
    orderbook: 0.08
    derivatives: 0.14
  mean_revert:
    trend: 0.15
    momentum: 0.22
    volatility: 0.13
    flow: 0.22
    orderbook: 0.13
    derivatives: 0.15
  chop:
    trend: 0.1
    momentum: 0.2
    volatility: 0.2
    flow: 0.25
    orderbook: 0.15
    derivatives: 0.1
filters:
  avoid_funding_minutes: 12     # extended blackout window (was 5)
  atr_gate_pct: 60
  adx_min: 20
  tr_compression_max: 0.25
engine:
  scoring_weights:
    trend: 0.5
    momentum: 0.5
    volatility: 0.0
  thresholds:
    enter: 0.1
    exit: 0.4
  risk:
    max_spread_pct:
      default: 0.02   # tightened from 0.06 for execution hygiene
      1000SHIBUSDT: 0.1
ensemble:
  min_score: 0.05
  majority_threshold: 0.5
  veto_trend_flip: true
  veto_band_pierce: true
  vote_threshold:
    trend: 0.6
    mean_revert: 0.58
    chop: 0.6
    mixed: 0.6
  min_agree:
    trend: 2
    mean_revert: 2
    chop: 2
    mixed: 2
  margin_of_victory: 0.08
  confidence_floor: 0.65   # was 0.60
  use_prob_mass: true
correlation:
  enabled: true
  lookback_periods: 200
  cluster_threshold: 0.7
  hysteresis: 0.1
  refresh_interval_bars: 50
veto:
  near_funding_window_min: 12   # was 20; now 10-15 min window
  wide_spread_bps: 6
  enable_liq_spike_contra: true
  enable_cvd_alignment: false
  enable_depth_thin_check: true
confluence:
  map:
    5m: 15m
    15m: 1h
    1h: 4h
  require_regime_align: true
alpha:
  funding:
    enabled: true
    source: csv
    dir: data/funding
    fallback_rate: 0.0001
  cvd:
    enabled: true
    method: ohlcv_proxy
    lookback: 200
    slope_window: 20
    slope_threshold: 0.1
  liquidations:
    enabled: true
    source: csv
    dir: data/liquidations
    spike_window: 50
    spike_zscore: 3.0
  depth:
    enabled: true
    exchanges:
    - binance
    - bybit
    thin_spread_bps: 12
    min_top_qty: 0.0
news_filter:
  enabled: true
  file: data/calendar/events.json
  window_minutes: 30
  min_severity: 2
portfolio:
  max_exposure_per_symbol: 1000.0
  max_exposure_per_cluster: 3000.0
  max_net_exposure: 5000.0
  max_margin_pct: 50.0
  global_entry_budget: 0
  max_total_positions: 10
  max_positions_per_symbol: 3
brakes:
  min_spacing_sec_cluster: 300
  daily_loss_soft_limit_pct: 2.0
  daily_loss_hard_limit_pct: 4.0
  streak_cooldown_trades: 3
  streak_cooldown_hours: 12
sizing:
  vol_risk_scale_pct: 0.5
  base_risk_pct: 0.01
  kelly_cap: 0.75
  rr_fallback: 1.2
sizer:
  enabled: true
  base_risk_pct: 0.5
  min_risk_pct: 0.25
  max_risk_pct: 1.0        # allow scale only up to 1.0% (was 0.75%)
  vol_target:
    method: atr
    lookback_bars: 14
    target_R_multiple: 1.0
    vol_floor_bps: 20
  conviction:
    use_meta: true
    use_mtc: true
    use_liquidity: true
  meta_anchor: 0.60   # shift anchor to reflect higher regime/prob threshold
  meta_span: 0.15
  mtc_bonus: 1.15
  mtc_partial: 0.75
  liquidity_dampen: 0.75
  kelly:
    enabled: true
    cap_fraction: 0.25
    win_R: 1.0
    loss_R: 1.0
  dd_scaler:
    enabled: true
    thresholds:
    - dd: 0.05
      mult: 0.75
    - dd: 0.1
      mult: 0.5
    - dd: 0.15
      mult: 0.33
    recovery_steps: 3
  per_symbol:
    max_risk_pct: 0.75
    max_position_value_pct: 20
  portfolio:
    max_gross_risk_pct: 2.0
    max_net_long_pct: 3.0
    max_net_short_pct: 3.0
  rounding:
    step_size: 0.0001
    notional_step: 10
  safety:
    min_notional: 25
    max_leverage: 10
execution:
  mode: ultra_fast
  max_slippage_pct: 0.05
  use_orderbook_liquidity: true
  min_orderbook_depth: 5
  retry_attempts: 3
  smart_order_routing: true
  cancel_stale_orders: true
  cancel_timeout_sec: 2.5
  iceberg_orders: false
portfolio_risk:
  enabled: true
  lookback_bars: 288
  min_bars: 96
  clusters:
    BTCUSDT: btc_beta
    ETHUSDT: btc_beta
    SOLUSDT: sol_ecosys
    ARBUSDT: eth_l2
    OPUSDT: eth_l2
  max_cluster_risk_pct:
    btc_beta: 0.9
    eth_l2: 0.6
    sol_ecosys: 0.5
  target_scheme: ERC
  rebalance_strength: 0.5
  corr_floor: 0.2
  corr_penalty: 0.5
  max_gross_risk_pct: 2.5
  max_net_long_pct: 3.5
  max_net_short_pct: 3.5
  rebalance_interval_bars: 6
  dry_run: false
risk_model:
  enabled: true
  base_risk_pct: 0.02
  max_leverage: 10
  min_confidence: 0.60    # tightened from 0.55
  regime_risk:
    trend: 1.2
    mean_revert: 1.0
    chop: 0.5
  atr_multiplier_stop: 2.5
  atr_multiplier_tp: 3.0
  tighten_tp_on_liq_cluster: true
  liq_tp_tighten_factor: 0.7
funding_rate_provider:
  refresh_interval_minutes: 15
transport:
  telegram:
    enabled: true
    bot_token: null
    chat_id: null
    message_template: '{pair} | {side} | ENTRY:{entry} | SL:{sl} | TP:{tp} | Lev:{lev}
      | p:{p_win:.2f} | regime:{regime} | veto:{veto_flags} | code:{reason}'
  dry_run: false
backtest:
  start_date: '2023-01-01'
  end_date: '2023-01-31'
  data:
    provider: csv
    base_path: data
    cache_path: .cache/data
  execution:
    initial_capital: 10000.0
    default_size_pct: 1.0
    fee_bps: 4.0
    slippage_model: atr
    tp_pct: 0.05
    sl_pct: 0.05
    max_bars_in_trade: 36
reports:
  output_dir: reports
logging:
  level: DEBUG
batch_run:
  symbols:
  - BTCUSDT
  - ETHUSDT
  - SOLUSDT
  - BNBUSDT
  - XRPUSDT
  - DOGEUSDT
  - ADAUSDT
  - AVAXUSDT
  - LINKUSDT
  - TONUSDT
  - TRXUSDT
  - DOTUSDT
  - NEARUSDT
  - ATOMUSDT
  - LTCUSDT
  - BCHUSDT
  - ARBUSDT
  - APTUSDT
  - MATICUSDT
  - SUIUSDT
  timeframes:
  - 1m
  - 3m
  - 5m
  - 15m
  start_date: '2023-10-01'
  end_date: '2024-12-31'
  max_parallel_workers: 6
  reuse_cache: true
  walk_forward:
    enabled: false
    train: 3m
    test: 3w
    advance: 3w
portfolio_hedge:
  enabled: true
  leader: BTCUSDT
  timeframe: 5m
  lookback_bars: 288
  shrinkage_lambda: 0.1
  corr_threshold_high: 0.55
  beta_band:
    min: -0.15
    max: 0.15
  beta_hard_cap: 0.25
  rebalance:
    min_notional: 0.005
    cooloff_bars: 3
  costs:
    taker_fee: 0.0004
    slippage_model: atr
    funding_penalty_perc_per_day: 0.03
  cluster_map:
    BTCUSDT: majors
    ETHUSDT: majors
    SOLUSDT: l1_alt
  cluster_caps:
    majors: 0.6
    l1_alt: 0.4
  leader_bias:
    trend_up_beta_target: 0.05
    trend_down_beta_target: -0.05
  open_guard:
    block_if_exceeds_beta_cap: true
    downscale_if_over_band: true
    downscale_factor: 0.5
risk:
  adaptive_exits:
    enabled: true
    atr_lookback: 14
    atr_mult_stop: 1.2
    atr_mult_target: 2.5
    min_stop_pct: 0.003
    max_stop_pct: 0.02
    regime_multiplier:
      high_vol: 1.6
      low_vol: 0.8
      chop: 0.7
      trending: 1.3
    structural_confluence: true
    swing_lookback: 12
    breakeven_enable: true
    breakeven_trigger_rr: 1.2
    trailing_enable: true
    trailing_type: atr
    trailing_step_mult: 1.0
    partial_tp:
      enabled: true
      levels:
      - rr: 1.5
        pct: 0.5
      - rr: 3.0
        pct: 0.5
  broker_sim:
    enabled: true
    rng_seed: 42
    venue_defaults:
      maker_fee_bps: -1.0
      taker_fee_bps: 4.0
      cancel_timeout_ms: 2500
      max_retries: 2
    venues:
      BINANCE:
        latency_ms:
          submit:
            dist: lognorm
            mu: 4.5
            sigma: 0.35
            min: 10
            max: 120
          cancel:
            dist: lognorm
            mu: 4.2
            sigma: 0.35
            min: 8
            max: 100
          modify:
            dist: lognorm
            mu: 4.2
            sigma: 0.35
            min: 8
            max: 100
          match:
            fixed: 5
        slippage:
          impact_factor: 0.65
          jitter_bps:
            dist: normal
            mean: 0.0
            std: 0.6
            clip: 2.0
      BYBIT:
        latency_ms:
          submit:
            dist: lognorm
            mu: 4.7
            sigma: 0.4
            min: 12
            max: 150
          cancel:
            dist: lognorm
            mu: 4.4
            sigma: 0.4
            min: 10
            max: 120
          modify:
            dist: lognorm
            mu: 4.4
            sigma: 0.4
            min: 10
            max: 120
          match:
            fixed: 7
        slippage:
          impact_factor: 0.75
          jitter_bps:
            dist: normal
            mean: 0.0
            std: 0.8
            clip: 2.5
    orderbook:
      levels: 10
      top_depth_floor: 0.5
      rebuild_from: bar+micro
    policies:
      post_only_reject_if_cross: true
      fill_on_touch_for_limit: false
      partial_fill_min_ratio: 0.1
      iceberg_supported: false
auto_stop_opt:
  enabled: true
  mode: atr
  grid:
    atr_mults:
    - 0.6
    - 0.8
    - 1.0
    - 1.2
    - 1.4
    - 1.8
    - 2.2
    - 2.8
    pct_mults:
    - 0.3
    - 0.4
    - 0.5
    - 0.7
    - 1.0
    - 1.5
    - 2.0
  constraints:
    min_winrate: 0.42
    max_mdd_pct: 12.0
    min_trades: 60
  regime_keys:
  - chop
  - trend
  - mean_revert
  - momentum
  lookback_days: 240
  rebalance_days: 7
  validation:
    method: walk_forward
    slices: 6
    purge_bars: 12
    embargo_bars: 12
  objective: expectancy
  tie_breaker: pf
  output_path: models/stop_opt/stop_table.yaml
