# Shadow Mode Test Configuration
# Run realtime with NO ORDERS (shadow mode) to validate sniper enforcement

runtime:
  symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT"]  # 3 symbols for focused testing
  timeframes: ["1m", "3m", "5m", "15m"]       # MTF confirmation test
  primary_timeframe: "5m"
  
  sniper_mode:
    enabled: true
    mtf_confirm: true
    max_signals_per_hour: 2
    daily_signal_cap: 6
    cooldown_bars: 10

# SHADOW MODE - NO LIVE ORDERS BUT REAL TELEGRAM NOTIFICATIONS
transport:
  telegram:
    enabled: true
    message_template: "🧪 SHADOW | {pair} | {side} | ENTRY:{entry} | SL:{sl} | TP:{tp} | Lev:{lev} | p:{p_win:.2f} | regime:{regime} | veto:{veto_flags} | sniper:{sniper_status}"
  dry_run: false  # CHANGED: Enable Telegram notifications for shadow testing
  
# Override: CRITICAL SHADOW MODE PROTECTION - No orders even with dry_run=false
shadow_mode: true  # This flag ensures NO ORDERS are placed regardless of transport.dry_run

# Prometheus metrics for monitoring
prometheus:
  enabled: true
  port: 8000

# Redis for distributed counters (if available)
redis:
  enabled: true
  host: "localhost"
  port: 6379
  db: 0

# Enhanced logging for shadow test
logging:
  level: "INFO"

# Minimal position sizing for shadow calculation
sizing:
  base_risk_pct: 0.010  # 1% risk for shadow calculations
