# Walk-Forward Analysis Configuration

walk_forward_config:
  # Defines the overall start and end dates for the entire analysis
  analysis_start_date: "2022-01-01"
  analysis_end_date: "2024-01-01"

  # Rolling window parameters
  window:
    train_period: "6m" # 6 months
    test_period:  "1m" # 1 month
    advance_by:   "1m" # How much to slide the window forward each iteration

  # Data cleansing parameters
  data_rules:
    purge_period: "5d" # 5 days
    embargo_period: "5d" # 5 days

# List of symbols to include in this backtest run
symbols:
  - "BTC-PERP"
  - "ETH-PERP"
  - "SOL-PERP"

# Versioning for reproducibility
version_info:
  strategy_version: "v1.2.3"
  config_version: "1.0"
  data_commit_hash: "a1b2c3d4" # Git hash of the data version used